### ISSUE TITLE
Server Updates

### ISSUE THREAD

**Issue by mytlogos** [mytlogos/enterprise-lister#30]
# Update on-demand
Let user trigger update.

## Todo
- [ ] Create a View about the current Server
    - current version should be visible
    - check if next version is available (when visiting view)
    - add an upgrade button which should trigger the upgrade of the server

- [ ] Create an API endpoint for triggering a server update
- [ ] create a general upgrade script

## Update Steps

1. Identify Release
2. git Pull the sources of the destination release
3. download the dist tar files of server and website
4. (Notify User of downtime) and close server sockets, kill crawler
    - user should be warned not to change the current view, so user can be notified in case of server crash
5. Start new Server process:
    - Spawn another server process (not a child one)
       - former server can observe if process crashed and resume operation in case of failure or kill itself on success
    - kill itself so pm2 (or another process manager) restarts it
       - cannot resume automatically, needs direct intervention on server machine

# Alternative: Automatic Deploy
Should be better in my case, as i do not want to upgrade the server manually each time by pressing a button.
More tests are need to ensure that generating a new release does not break something, that prevents the server from operating normally.

## TODO
- [ ] Add SSH Credentials to Jenkins Server
    - use ssh key instead of password credential
    - create a new user with privileges limited to the project directory in deploy server
- [ ] Add `Deploy` Stage to Jenkinsfile

## Update Steps

1. Identify Release and check if new release is available
    - just in case new commits but not a new release triggered the build
2. git Pull the sources of the destination release
3. download the dist tar files of server and website
4. use pm2 restart to restart server
5. optional: observe for a minute if anything crashed
   - in case it crashed, recover by rolling back to the previous working release?
